[project]
name = "citetrace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tssssk", email = "165155073+tskwak111@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
citetrace = "citetrace:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.5",
]
