apiVersion: v1
kind: Service
metadata:
  name: {{ include "citetrace.fullname" . }}-api
  labels:
    {{- include "citetrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.api.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "citetrace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "citetrace.fullname" . }}-worker
  labels:
    {{- include "citetrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "citetrace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
